Fix Permissions Manager and Friends
Atlas-Rhythm/Hive pull request #97
Opened 2021-12-12 04:46 UTC by Caeden117

This PR performs the following fixes:
- Changes the `PermissionsManager` constructor in DryIoc to allow an injected `IEnumerable<(string, Delegate)>`
  - Thus allowing external plugins (Like Tags) to register their own functions for the permissions system
  - This works fine on a very barebones Hive instance (with only a Rule Provider plugin installed so Hive can start)
- Added a wrapper method for registering new functions for the permission system
- Combine `hive.mods.filter` and `hive.mod.filter` permission rules into *just* `hive.mod.filter`
- Fix launchSettings.json to use the `net6.0` working directory
  - I guess I had to explicitly change this so VS Debugging actually pointed to the right directory

2021-12-14 00:54 UTC, nike4613 requested changes
LGTM, minor formatting issues.

2021-12-14 00:54 UTC, nike4613 commented on src/Hive/Startup.cs
> +            container.Register(Made.Of(() => new PermissionsManager<PermissionContext>(Arg.Of<IRuleProvider>(), Arg.Of<Permissions.Logging.ILogger>(), ".", Arg.Of<IEnumerable<(string, Delegate)>>()))
This line could probably do to be wrapped at this point.

2021-12-19 04:00 UTC, sc2ad approved these changes

2021-12-19 04:58 UTC, nike4613 approved these changes

2021-12-19 04:58 UTC, merged